import React from 'react'
import GreenBox from '../../../resources/boxes/greenbox.png';
import DiscordButton from '../../../resources/buttons/discord-green.png';

function JoinCommunityBlock() {
  return (
    <div style={styles.container}>
      <div style={styles.phaseContainer}>
        <img src={GreenBox} alt="" style={styles.phaseImage} />
        <div style={styles.phaseText}>
          <div style={styles.phaseTitle}>
            JOIN OUR COMMUNITY
          </div>
          <div style={styles.phaseParagraph}>
            The FrogBoiz anthem is to vote, toke, and donate hope together. The boiz wanna help in the development of the creative philanthropy space, focusing on the NFT ecosystem in particular. We hope to deliver life changing infrastructure and development for fighting global warming around the world by donating chunks of mint and royalties generated by the project.
          </div>
          <div style={styles.buttonContainer}>
            <img style={styles.button} src={DiscordButton} alt="" />
          </div>
        </div>
      </div>
    </div>
  )
}

const styles = {
  container: {
    backgroundColor: '#2b032f',
    display: 'flex',
    flexDirection: 'column',
    flexShrink: '0',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    minHeight: '90vh',
  },
  phaseContainer: {
    margin: 'auto',
    marginTop: '128px',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    width: '90%',
    height: 'auto',
    fontFamily: 'VideoGame',
    color: 'white',
  },
  phaseImage: {
    width: '100%',
    height: 'auto',
  },
  phaseText: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    position: 'absolute',
    width: 'calc(100% - 144px)',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  phaseParagraph: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: '24px',
    padding: '18px 0',
  },
  phaseTitle: {
    color: '#71bd4b',
    fontSize: '48px',
    fontWeight: 'bold',
    fontFamily: 'VideoGame',
  },
  buttonContainer: {
    width: '240px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
  },
  button: {
    width: '100%',
  }
}

export default JoinCommunityBlock
